POST http://localhost:3003/api/blog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpZCI6IjY2YzRjODk1ODZhNGIzMzg2N2I2NGQyYSIsImlhdCI6MTcyNDE3MjQ5Nn0.Pte1kIXZ0pMF6X286dIFQoh5hNRB5CJtA2y_FNFj50o

{
	"title":"second blog created to check userExtractor middleware",
	"url": "a random url",
	"likes":13
}

